name: Lint and Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm run prettier

      - name: Run ESLint
        run: pnpm run lint

      - name: Build Next.js app
        run: pnpm run build
